/** Identificadores guardados en `email_send_logs.event_type`. */
export const PuntooMailEvent = {
  CLOSED_BOOKING_CONFIRMED: 'CLOSED_BOOKING_CONFIRMED',
  OPEN_MATCH_PUBLISHED: 'OPEN_MATCH_PUBLISHED',
  OPEN_MATCH_PLAYER_JOINED_ORGANIZER: 'OPEN_MATCH_PLAYER_JOINED_ORGANIZER',
  OPEN_MATCH_PLAYER_JOINED_SELF: 'OPEN_MATCH_PLAYER_JOINED_SELF',
  OPEN_MATCH_CONFIRMED_ALL: 'OPEN_MATCH_CONFIRMED_ALL',
  OPEN_MATCH_LEAVE_SELF: 'OPEN_MATCH_LEAVE_SELF',
  OPEN_MATCH_LEAVE_ORGANIZER: 'OPEN_MATCH_LEAVE_ORGANIZER',
  OPEN_MATCH_LEAVE_FROM_FULL: 'OPEN_MATCH_LEAVE_FROM_FULL',
} as const;
